### ISSUE TITLE
SelectedNode not working? 

### ISSUE THREAD

**Issue by BartShoot** [MakesYT/NodifyM.Avalonia#2]
Hi, I'm moving my WPF app that was using Nodify to Avalonia and was so far using it without much problems but I now need SelectedNode property and it doesn't seem to work? 
EditorView.axaml
```axaml
<controls:NodifyEditor x:Name="Editor" ... SelectedItem="{Binding SelectedNode}">
```
EditorViewModel.cs
```csharp
[ObservableProperty] private NodeViewModelBase _selectedNode;
```
It stays null the whole time as far as I can see. Is it problem on my side? Or does it need to be fixed?
My project if you need to look into it https://github.com/BartShoot/NoodleCV/tree/main/NoodleCV.App
If you point me in the right direction I could try to contribute PR with the fix

**Comment by MakesYT** [comment]
Fixed, if there are any issues. Feel free to reopen the issue
